<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Helpers.fs" />
    <Compile Include="DocumentTests.fs" />
    <Compile Include="UserQuotaTests.fs" />
    <Compile Include="IntegrationTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\Domain\Domain.fsproj" />
    <ProjectReference Include="..\..\src\Web\Web.fsproj" />
    <PackageReference Include="FCQRS" Version="6.0.0-preview21" />
    <PackageReference Include="Expecto" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.*" />
  </ItemGroup>

</Project>
