<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Db.fs" />
    <Compile Include="Projection.fs" />
    <Compile Include="Endpoints.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.fsproj" />
    <PackageReference Include="FCQRS" Version="6.0.0-preview26" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.*" />
    <PackageReference Include="FCQRS.Model" Version="6.0.0-*" />
    <PackageReference Include="Dapper" Version="2.*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.*" />
    <PackageReference Include="Akka.Streams" Version="1.5.*" />
    <PackageReference Include="Akka.Persistence.Query" Version="1.5.*" />
  </ItemGroup>

</Project>
